global-styling:
  version: VERSION
  css:
    base:
      /themes/contrib/claro/css/dist/base/elements.css: {}
      /themes/contrib/claro/css/dist/base/typography.css: {}
      /themes/contrib/claro/css/dist/base/print.css: {}
    component:
      /themes/contrib/claro/css/dist/components/accordion.css: {}
      /themes/contrib/claro/css/dist/components/action-link.css: {}
      /themes/contrib/claro/css/dist/components/content-header.css: {}
      /themes/contrib/claro/css/dist/components/container-inline.css: {}
      /themes/contrib/claro/css/dist/components/container-inline.module.css: {}
      /themes/contrib/claro/css/dist/components/breadcrumb.css: {}
      /themes/contrib/claro/css/dist/components/button.css: {}
      /themes/contrib/claro/css/dist/components/details.css: {}
      /themes/contrib/claro/css/dist/components/divider.css: {}
      /themes/contrib/claro/css/dist/components/messages.css: {}
      /themes/contrib/claro/css/dist/components/entity-meta.css: {}
      /themes/contrib/claro/css/dist/components/fieldset.css: {}
      /themes/contrib/claro/css/dist/components/form.css: {}
      /themes/contrib/claro/css/dist/components/form--checkbox-radio.css: {}
      /themes/contrib/claro/css/dist/components/form--checkbox-radio--ie.css: {}
      /themes/contrib/claro/css/dist/components/form--field-multiple.css: {}
      /themes/contrib/claro/css/dist/components/form--managed-file.css: {}
      /themes/contrib/claro/css/dist/components/form--text.css: {}
      /themes/contrib/claro/css/dist/components/form--select.css: {}
      /themes/contrib/claro/css/dist/components/help.css: {}
      /themes/contrib/claro/css/dist/components/image-preview.css: {}
      /themes/contrib/claro/css/dist/components/menus-and-lists.css: {}
      /themes/contrib/claro/css/dist/components/modules-page.css: {}
      /themes/contrib/claro/css/dist/components/node.css: {}
      /themes/contrib/claro/css/dist/components/page-title.css: {}
      /themes/contrib/claro/css/dist/components/pager.css: {}
      /themes/contrib/claro/css/dist/components/skip-link.css: {}
      /themes/contrib/claro/css/dist/components/tables.css: {}
      /themes/contrib/claro/css/dist/components/table--file-multiple-widget.css: {}
      /themes/contrib/claro/css/dist/components/search-admin-settings.css: {}
      /themes/contrib/claro/css/dist/components/tablesort-indicator.css: {}
      /themes/contrib/claro/css/dist/components/system-status-report-general-info.css: {}
      /themes/contrib/claro/css/dist/components/system-status-report.css: {}
      /themes/contrib/claro/css/dist/components/system-status-report-counters.css: {}
      /themes/contrib/claro/css/dist/components/system-status-counter.css: {}
      /themes/contrib/claro/css/dist/components/tabs.css: {}
      /themes/contrib/claro/css/dist/components/views-ui.css: {}
    theme:
      /themes/contrib/claro/css/dist/theme/colors.css: {}
    layout:
      /themes/contrib/claro/css/dist/layout/breadcrumb.css: {}
      /themes/contrib/claro/css/dist/layout/local-actions.css: {}
      /themes/contrib/claro/css/dist/layout/layout.css: {}
  dependencies:
    - system/admin
    - core/jquery
    - core/drupal
    # Claro has small and extra small variation for most of the control elements
    # such as inputs, action links, buttons, dropbuttons. For usability and
    # accessibility reasons, we keep target sizes big enough on touch screen
    # devices (by not making these elements smaller than their default size).
    # Modernizr is used for recognising whether user is using a touch device or
    # not. This allows conditionally rendering small variation of the control
    # elements on non-touch devices. In some cases, such as when rendering
    # links, it is hard recognize when Modernizr should be attached, therefore
    # it has to be always attached.
    - core/modernizr
    # @todo Remove 'claro/drupal-theme' from dependencies and add to core/drupal
    # extensions after https://www.drupal.org/node/3024975 is in.
    - claro/drupal-theme

node-form:
  version: VERSION
  css:
    layout:
      /themes/contrib/claro/css/dist/layout/node-add.css: {}
  dependencies:
    - node/form

maintenance-page:
  version: VERSION
  js:
    /themes/contrib/claro/js/mobile.install.js: {}
  css:
    theme:
      /themes/contrib/claro/css/dist/theme/maintenance-page.css: {}
  dependencies:
    - system/maintenance
    - edtalks_admin/global-styling

install-page:
  version: VERSION
  js:
    /themes/contrib/claro/js/mobile.install.js: {}
  css:
    theme:
      /themes/contrib/claro/css/dist/theme/install-page.css: {}
  dependencies:
    - edtalks_admin/maintenance-page

drupal.nav-tabs:
  version: VERSION
  js:
    /themes/contrib/claro/js/nav-tabs.js: {}
  dependencies:
    - core/matchmedia
    - core/jquery
    - core/drupal
    - core/jquery.once
    - core/drupal.debounce
    - core/collapse

drupal.responsive-detail:
  version: VERSION
  js:
    /themes/contrib/claro/js/responsive-details.js: {}
  dependencies:
    - core/matchmedia
    - core/matchmedia.addListener
    - core/jquery
    - core/jquery.once
    - core/collapse

edtalks_admin.jquery.ui:
  version: VERSION
  css:
    component:
      /themes/contrib/claro/css/dist/components/jquery.ui/theme.css: { weight: -1 }

edtalks_admin.drupal.dialog:
  version: VERSION
  css:
    theme:
      /themes/contrib/claro/css/dist/components/dialog.css: {}

ckeditor-dialog:
  version: VERSION
  css:
    theme:
      /themes/contrib/claro/css/dist/theme/ckeditor-dialog.css: {}

ckeditor-editor:
  version: VERSION
  css:
    theme:
      /themes/contrib/claro/css/dist/theme/ckeditor-editor.css: {}

tour-styling:
  version: VERSION
  css:
    theme:
      /themes/contrib/claro/css/dist/components/tour.theme.css: {}

media-form:
  version: VERSION
  css:
    layout:
      /themes/contrib/claro/css/dist/components/media.css: {}
  dependencies:
    - media/form

image-widget:
  version: VERSION
  css:
    component:
      /themes/contrib/claro/css/dist/layout/image-widget.css: {}

system.admin:
  version: VERSION
  css:
    component:
      /themes/contrib/claro/css/dist/components/system-admin--admin-list.css: { weight: -10 }
      /themes/contrib/claro/css/dist/components/system-admin--links.css: { weight: -10 }
      /themes/contrib/claro/css/dist/components/system-admin--modules.css: { weight: -10 }
      /themes/contrib/claro/css/dist/components/system-admin--panel.css: { weight: -10 }
      /themes/contrib/claro/css/dist/components/system-admin--status-report.css: { weight: -10 }
    layout:
      /themes/contrib/claro/css/dist/layout/system-admin--layout.css: { weight: -10 }
  dependencies:
    - edtalks_admin/card

drupal-theme:
  version: VERSION
  js:
    /themes/contrib/claro/js/theme.js: {}
  dependencies:
    - core/drupal

# @todo Remove after https://www.drupal.org/node/3024975 is in.
drupal.tableselect:
  version: VERSION
  js:
    /themes/contrib/claro/js/claro.tableselect.js: {}

# @todo Remove after https://www.drupal.org/node/3024975 is in.
media_library.view:
  version: VERSION
  js:
    /themes/contrib/claro/js/claro.media_library.view.js: {}

autocomplete:
  version: VERSION
  js:
    /themes/contrib/claro/js/autocomplete.js: {}

drupal.shortcut:
  version: VERSION
  css:
    # @todo move this to components after
    #   https://www.drupal.org/project/drupal/issues/3045467 is in.
    theme:
      /themes/contrib/claro/css/dist/components/shortcut.css: {}

details-focus:
  js:
    /themes/contrib/claro/js/details.js: {}

ajax:
  js:
    /themes/contrib/claro/js/ajax.js: {}

form.password-confirm:
  css:
    component:
      /themes/contrib/claro/css/dist/components/form--password-confirm.css: {}
  js:
    /themes/contrib/claro/js/user.js: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/jquery.once
    - edtalks_admin/global-styling

views:
  css:
    component:
      /themes/contrib/claro/css/dist/components/views-exposed-form.css: {}

messages:
  js:
    /themes/contrib/claro/js/messages.js: {}

card:
  css:
    component:
      /themes/contrib/claro/css/dist/layout/card-list.css: {}
      /themes/contrib/claro/css/dist/components/card.css: {}

vertical-tabs:
  css:
    component:
      /themes/contrib/claro/css/dist/components/vertical-tabs.css: {}
  dependencies:
    - edtalks_admin/global-styling

file:
  css:
    component:
      /themes/contrib/claro/css/dist/components/file.css: {}
